### ISSUE TITLE
Running Visualization in Gama

### ISSUE THREAD

**Issue by LAAP** [CityScope/CityLab_Biobio#6]
@amcarrero  I am trying to run the visualization in GAMA, but the USER Model is ampty.

BTW, the test looks like fantastic

<img width="1792" alt="Screen Shot 2023-09-28 at 10 11 54 AM" src="https://github.com/CityScope/CityLab_Biobio/assets/19315213/b7013c14-637b-401f-abeb-8568e0f00725">

**Comment by LAAP** [comment]
OK, now it has an error when running:

<img width="1792" alt="Screen Shot 2023-09-28 at 11 17 57 AM" src="https://github.com/CityScope/CityLab_Biobio/assets/19315213/12b933ac-ff1d-42bc-8a2c-624cee104d01">

**Comment by agrignard** [comment]
@LAAP in general when you have an error (it's a compialtion error not an runnign error) it would be useful that you also explain what and where is the error. The error is shown with a red cross on the text editor (you can actually see it on your screenshot with the tiny red rectangle on the lower left side of your text editor)


I wouldn't be surprised if it's just a question of the version you are using. Which version of GAMA are you using? 

For now on most of the project in CityScope should use Gama 1.9.x (I have updated most of the CityScope Repository in April 2023 to make all the model compatible with 1.9).

So I would susggest to download the 1.9 version here https://gama-platform.org/download

**Comment by agrignard** [comment]
Yes the factorization can be a good idea (even if sometimes for beginners only one file ease the usage of the model) but it's up to you. However what I don't get is that the model is already split in the main branche isn't it? Then I am not sure to see the difference between this branch and the current one. If it's not difficult I would suggest to merge this PR as soon as possible to avoid a significant divergence of the 2 branch

**Comment by LAAP** [comment]
HI @agrignard ,updating my GAMA. 
I let the split question to @amcarrero

**Comment by LAAP** [comment]
Mmmm. Mac version GAMA 1.9.2 does not update at my Mac, hahaah!

**Comment by agrignard** [comment]
What do you mean by updating? are you downl;oading the last version? Then you should have a .dmg to install Gama.app and then you run it (by rick clicing on gama.app and then open)

what is the Os you are using? is your mac a M1?

**Comment by agrignard** [comment]
@LAAP did you manage to make Gama work on your computer?
